DECLARE 
    VRESULT VARCHAR2(200);
    VSQL1 VARCHAR2(32767);
    VSQL2 VARCHAR2(32767);
    VSQL3 VARCHAR2(32767);
    VSQL4 VARCHAR2(32767);
    VSQL5 VARCHAR2(32767);
    VSQL6 VARCHAR2(32767);
    
BEGIN
    -- 1) Add a new temp column of type CLOB
	VSQL1:= 'ALTER TABLE ASRESTSERVICEQUERY ADD (QUERYVALUE_TMP CLOB)';
	-- 2) Copy existing data into the temp column
	VSQL2:= 'UPDATE ASRESTSERVICEQUERY SET QUERYVALUE_TMP = QUERYVALUE';
	VSQL3:= 'COMMIT';
	-- 3) Drop the old VARCHAR2 column
	VSQL4:= 'ALTER TABLE ASRESTSERVICEQUERY DROP COLUMN QUERYVALUE';
	-- 4) Rename the CLOB column to the original name
	VSQL5:= 'ALTER TABLE ASRESTSERVICEQUERY RENAME COLUMN QUERYVALUE_TMP TO QUERYVALUE';
	-- 5) Add the not null contraint to the QueryValue column
	VSQL6:= 'ALTER TABLE ASRESTSERVICEQUERY MODIFY (QUERYVALUE NOT NULL)';
	VRESULT := NULL;

    EXECUTESQL ( VSQL1, VRESULT );
    EXECUTESQL ( VSQL2, VRESULT );
    EXECUTESQL ( VSQL3, VRESULT );
    EXECUTESQL ( VSQL4, VRESULT );
    EXECUTESQL ( VSQL5, VRESULT );
    EXECUTESQL ( VSQL6, VRESULT );

END;
/