DECLARE 

    VSQL1 VARCHAR2(32767);
    VSQL2 VARCHAR2(32767);
    VRESULT VARCHAR2(200);

BEGIN
VSQL1:='
    UPDATE ASACTIVITYMULTIVALUEFIELD SET TEXTVALUE = ''SRTP'', OPTIONTEXT = ''AsCodeCessionMode.SRTPLD''
    WHERE FIELDNAME = ''ReinsuranceForcedCessionMode'' AND TEXTVALUE = ''HRTP''
    ';
VSQL2:='
    UPDATE ASROLEFIELD SET TEXTVALUE = ''SRTP'', OPTIONTEXT = ''AsCodeCessionMode.SRTPLD''
    WHERE FIELDNAME = ''ReinsuranceForcedCessionMode'' AND TEXTVALUE = ''HRTP''
    ';
    
VRESULT := NULL;

EXECUTESQL ( VSQL1, VRESULT );
EXECUTESQL ( VSQL2, VRESULT );
    
END;
/